### PR TITLE
Sign certificate after setting extensions

### PR DESCRIPTION
**Pull request by lnattrass**
Not sure if you are accepting any pull requests for this - I can see it's under active development.

This changes around the signing so that it happens after any extensions are added to the certificate.

Also, I'm setting version 3 on the certificate by default too - hopefully that's not an issue?

Cheers

### CODE REVIEW

**Comment by mathiasertl** [comment]
Absolutely 100% accepting pull requests for this! Thanks a lot!

I'm actively writing tests right now, to get acceptable code coverage, which also found me a few bugs. When I get good coverage, I plan on making a release, hopefully soon.

A few questions about your pull request:

* on ca/django_ca/utils.py:112: Shouldn't this be ``cert.get_version()``? 
* What exactly does the certificate version do?
* Does the later signing of the certificate change anything or is it just a beauty-thing?

**Comment by mathiasertl** [comment]
On closer inspection I'm also not quite sure if it's correct to add the CRL/OCSP URLs to the CA certificate itself - the usage in line . The parameter is saved in the db later on (line 96 in your pull request) and used when signing the certificates, so signed certificates will have those extensions. 

I will compare the OCSP/CRL attributes of CAs in the wild and post my findings here. If you can shed some insight, I'm of course happy to hear it!

**Comment by lnattrass** [comment]
True! Hmm right my bad.

**Comment by lnattrass** [comment]
I'm just fixing the things you've found up :)
Shouldn't be too long...

**Comment by lnattrass** [comment]
I think you're right - I can't find a CA that has OCSP or CRL's defined.

So in summary, this change moves the signing to happen after the extensions are added.
The certificate was showing as invalid when the extensions were added post-signing.

Also have fixed the typo to enable X509 V3, which basically enables additional properties on the certificate as far as I can see.

**Comment by mathiasertl** [comment]
Excellent, will merge when I get home!

**Comment by mathiasertl** [comment]
I'm sorry but I have a follow up question on this: Where/When/How was the certificate showing up as invalid?

I'm trying to write a test case testing for the error you got, but I can't really come up with any test that says my certificate is wrong :-/

**Comment by lnattrass** [comment]
Well, I had created a root ca for some testing and couldn't get it to validate certs on a website.

I ended up creating some code to try to work out why.
Here's a gist which should show what I was seeing (Python2) https://gist.github.com/lnattrass/a8981bea7f874e7856af78c14999ae24

I haven't found an openssl command to cover this one yet, I can only replicate it by opening the certificate from Windows..

**Comment by mathiasertl** [comment]
Thanks for the pull request again, I just merged this. 

It is somewhat frustrating, I found no evidence whatsoever that the generated certificates are invalid besides what you experienced on Windows. I tried a certificate generated via `fab init_demo` in both Firefox and Chromium, tried the `openssl verify` command on both the ca certificate and the client certificate and tried various integrity functions I found in pyOpenSSL. Everything works fine, the certs seem all fine.

**Pull request merged**
