### PR TITLE
Fix #33 - Added missing migration and bump version

### LINKED ISSUE #33: Missing migration on pip
If you install django-ca using pip, and then use it on a django project, when you call makemigrations a new migration on the django-ca python library is created (if root, otherwise an error appears)

this is the migration:
```python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0006_auto_20170505_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='django_ca.CertificateAuthority'),
        ),
    ]
```

### PR DESCRIPTION
**Pull request by xkill**

### CODE REVIEW

**Comment by mathiasertl** [comment]
Please remove the version bump in setup.py, then I will merge this.

**Comment by xkill** [comment]
Done. Removed the commit with bump version.

**Comment by mathiasertl** [comment]
I've already added this migration in bda098bed478c4d4562a9c58a76d7d56b7677e01#diff-726266ba917c0905fa7fd0b003b12c1b

**Comment by mathiasertl** [comment]
And don't worry about being late. Wish I could be more responsive!

**Pull request closed without merging**
